theme: jekyll-theme-minimal

title: Felipe Lozano-Rojas
description: PhD(c) Pub. Affairs, Indiana University. My interests span from applied micro to social policy to public finance and economics. I use DS to answer my research questions.
google_analytics: [UA-139923660-1]
